version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: saber-database
      POSTGRES_USER: saber
      POSTGRES_PASSWORD: saber-password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/saber-data
volumes:
  pgdata:
